name: Docker Build and Run

on:
  workflow_dispatch:
jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Run Docker Container
      run: |
        docker build -t dk1 .
        docker run -d dk1 
